# Generated by Django 3.2.9 on 2021-11-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimilarSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=15)),
                ('source', models.CharField(max_length=500)),
            ],
        ),
    ]
